export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CUSTOMER_LIST="GET_CUSTOMER_LIST";
export const DELETE_CUSTOMER="DELETE_CUSTOMER";
export const GET_SPECIFIC_CUSTOMER="GET_SPECIFIC_CUSTOMER";
export const UPDATE_CUSTOMER="UPDATE_CUSTOMER";